pace-neutrons/Euphonic

- doc/source/calc_ins.rst
- doc/source/interpolate.rst
- doc/source/plot_disp.rst
- doc/source/plot_dos.rst
- doc/source/plot_sqw.rst
- doc/source/read_castep.rst
- doc/source/units.rst
- euphonic/_readers/_castep.py
- euphonic/data/bands.py
- euphonic/data/interpolation.py
- euphonic/data/phonon.py
- scripts/dispersion.py
- scripts/dos.py
- scripts/optimise_eta.py
- test/test_bands_data.py
- test/test_interpolation_data.py
- test/test_phonon_data.py
- test/test_reorder_freqs.py
- test/test_sqw_map.py
- test/test_structure_factor.py
Changes to implement new api XData(seedname) -> XData.from_castep(seedname). 
- Updated documentation
- Working tests
- Extendable to new interfaces
- Interpreter autocomplete
> 11 read from methods

- tox.ini
We will now be able to execute on any python version as tox will install it with conda.
> Use conda to build environment

- .gitignore
- Jenkinsfile
- test/run_tests.py
- tox.ini
Test results reporting in Jenkins
As a maintainer of Euphonic, I would like the test results to be archived and displayed on Jenkins itself.
Acceptance criteria:
- Failing tests are displayed on a graph in Jenkins
- For master, branch and pr pipelines
> Test results reporting

- Jenkinsfile
- release_tox.ini
- tests_and_analysis/test/run_tests.py
- tests_and_analysis/test/test_bands_data.py
- tests_and_analysis/test/test_dw_factor.py
- tests_and_analysis/test/test_interpolation_data.py
- tests_and_analysis/test/test_phonon_data.py
- tests_and_analysis/test/test_reorder_freqs.py
- tests_and_analysis/test/test_sqw_map.py
- tests_and_analysis/test/test_structure_factor.py
- tests_and_analysis/test/test_util.py
- tests_and_analysis/test/utils.py
- tox.ini
Run tests from pytest
As a maintainer of Euphonic, I would like to write tests in pytest and have legacy unittest tests run from pytest.
Acceptance criteria:
- Run current unittest tests from pytest
Notes:
- As we are now using the pytest runner the data path was not found using the old method, so I have used a new method and centralised it so it is easy to refactor in the future i.e. get_data_path()
- I have also reduced the verbosity of the install output as it was extremely long and hiding other important information
> 96 convert to pytest

- Jenkinsfile
- tox.ini
Add a webhook trigger using the jobs name to trigger jobs based on pushes to github
> Setup webhook correctly

- euphonic/_readers/_phonopy.py
> 44 force constants shape

- Jenkinsfile
- euphonic/plot/dos.py
- tests_and_analysis/jenkins_requirements.txt
- tests_and_analysis/static_code_analysis/run_analysis.py
> Fix pylint output

- tests_and_analysis/LinuxJenkinsfile
- tests_and_analysis/WindowsJenkinsfile
I accidentally broke the builds by changing the API token forgetting the name was hardcoded into Jenkinsfiles, replace with the correct api token here.
> Use correct API token

- CHANGELOG.rst
- doc/source/index.rst
- setup.py
> Add option for Python only install

- tests_and_analysis/LinuxJenkinsfile
- tests_and_analysis/WindowsJenkinsfile
Get the release version from the job base name and remove the v off the front
> Fix release tests

- tests_and_analysis/MacJenkinsfile
Created a Jenkinsfile to run on the "Euphonic Mac Pipeline"
> 106 mac os node

- CHANGELOG.rst
- c/load_libs.c
> Add extra search dir for libopenblas*dll, fixes #147

- CHANGELOG.rst
- euphonic/spectra.py
- tests_and_analysis/test/euphonic_test/test_spectrum1dcollection.py
Addresses #157
This has also resulted in some refactoring of all Spectra.broaden methods. I've added some minimal tests for now checking that `Spectrum1DCollection.broaden` produces the same results as calling each `Spectrum1D.broaden` individually. I may add some other tests once the PDOS stuff is in and there are more options for test data.
> 157 Add Spectrum1DCollection.broaden

- CHANGELOG.rst
- doc/source/dos-script.rst
- doc/source/dos.rst
- doc/source/intensity-map-script.rst
- doc/source/plotting.rst
- doc/source/powder-map-script.rst
- doc/source/qpoint-phonon-modes.rst
- doc/source/spectra.rst
- doc/source/structure-factor.rst
- doc/source/tutorials.rst
- euphonic/spectra.py
Updates changelog and documentation
Built docs can be seen at https://euphonic.readthedocs.io/en/116_pdos_docs/
> 116 PDOS Docs

- euphonic/brille.py
- euphonic/cli/check_brille_settings.py
- euphonic/cli/powder_map.py
- euphonic/cli/show_sampling.py
- euphonic/cli/utils.py
- euphonic/sampling.py
- setup.py
- tests_and_analysis/test/data/script_data/powder-map.json
- tests_and_analysis/test/script_tests/test_powder_map.py
Closes #206 
This introduces a tool for error estimation and analysis of Brille-interpolated results.
> 206 Brille sampling tool

- .github/workflows/run_tests.yml
- doc/source/force-constants.rst
- doc/source/qpoint-phonon-modes.rst
- euphonic/force_constants.py
- euphonic/qpoint_phonon_modes.py
- euphonic/structure_factor.py
* Updates the equations in the docstrings to match the conventions in the Euphonic paper
* Other small miscellaneous updates for clarity
> Small doc updates

- CHANGELOG.rst
- euphonic/force_constants.py
- tests_and_analysis/test/script_tests/test_dispersion.py
- tests_and_analysis/test/script_tests/test_intensity_map.py
- tests_and_analysis/test/script_tests/test_powder_map.py
Temporary workaround for #191 
Should be merged after #243
> Add workaround for segfault with openblas

- .github/workflows/run_tests.yml
- doc/requirements.txt
- doc/source/cite.rst
- doc/source/conf.py
- doc/source/dos.rst
- doc/source/force-constants.rst
- doc/source/plotting.rst
- doc/source/qpoint-frequencies.rst
- doc/source/qpoint-phonon-modes.rst
- doc/source/spectra.rst
- doc/source/structure-factor.rst
- doc/source/units.rst
- euphonic/force_constants.py
> Add Sphinx doctests

- setup.py
Author information is in CITATION.cff instead
> Remove author from setup.py

- CHANGELOG.rst
- euphonic/plot.py
- tests_and_analysis/test/euphonic_test/test_plot.py
> Allow 'color' to be passed to plot_1d

- .github/workflows/set_version.yml
This action doesn't make any changes to the code yet: to develop a workflow_dispatch action we need to have _something_ on the default branch so it can be
launched and tested.
> Create initial set_version.yml

- euphonic/spectra/base.py
> Make internal _cut_x_ticks a bit nicer to read/understand

- CHANGELOG.rst
- euphonic/spectra/base.py
- tests_and_analysis/test/euphonic_test/test_spectrum1d.py
- tests_and_analysis/test/euphonic_test/test_spectrum2d.py
> Implement alternate _bin_centres_to_bin_edges mode

- .github/workflows/release.yml
In support of #326 
We need _something_ on master to be able to run/test this from other branches.
> Create a stub release.yml to enable workflow dispatch

- euphonic/cli/utils.py
- euphonic/force_constants.py
- euphonic/io.py
- euphonic/plot.py
- euphonic/readers/castep.py
- euphonic/sampling.py
- euphonic/structure_factor.py
- euphonic/validate.py
- pyproject.toml
Some of the bigger / more-challenging / more-contentious ruff sections have been left until later, but we now have all the low-hanging fruit and some notes to guide future linting work.
> 388 Finished first pass through ruff rules list

- CONTRIBUTING.rst
> add CONTRIBUTING file
