pace-neutrons/Euphonic

CHANGELOG.rst
euphonic/_readers/_castep.py

Replace fixed number of line skips with a search for the line beginning 'Unit cell vectors'
This resolves #23

Removed fixed number of line skips

---

Jenkinsfile

We use the free package for conda to install python 3.6
Anvil removed this from being loaded as default, this fix loads that package so we can run python 3.6

Add append free channel to use python with conda

---

euphonic/data/interpolation.py
tests_and_analysis/test/test_dw_factor.py
tests_and_analysis/test/test_interpolation_data.py
tests_and_analysis/test/test_structure_factor.py

- This has a small effect on the structure factor (eigenvectors are very
sensitive to changes in the dynamical matrix) so also update test tolerances

Use upper dynamical matrix in Numpy diagonalisation. Fixes #47

---

euphonic/plot.py
scripts/neutron-band-structure.py
setup.py

Addressing Issue #84
- Refactor plot_2d to use NonUniformImage. This cleans up a lot of the plotting logic, taking care of the irregular spacing for us.
- Break actual axis plotting into separate function that can be re-used for custom/complex layouts, while plot_2d remains a "fire and forget" tool returning a Figure
- Allow Normalize object to be passed, in preparation for implementation of multi-part plot with common colour scale
- Dump script used for testing/prototyping into scripts directory; with a bit more work this should become a good tool for users.
Setting the plot aspect ratio is no longer a technical requirement as NonUniformImage manages this well. For now I will remove the feature; user-facing scripts would be able to set dimensions by manipulating the figure directly.
- …

Spectrum2D: rework plotting, provide a new user script

---

CHANGELOG.rst
euphonic/io.py
tests_and_analysis/test/euphonic_test/test_crystal.py
tests_and_analysis/test/euphonic_test/test_debye_waller.py
tests_and_analysis/test/euphonic_test/test_force_constants.py
tests_and_analysis/test/euphonic_test/test_qpoint_phonon_modes.py
tests_and_analysis/test/euphonic_test/test_spectrum1d.py
tests_and_analysis/test/euphonic_test/test_spectrum2d.py
tests_and_analysis/test/euphonic_test/test_structure_factor.py
tests_and_analysis/test/utils.py

Adds metadata to .json outputs describing the Euphonic version, and the class being written, to make it easier to automatically determine object types from files. This is to aid in reading files for command line tools, and came about as a result of https://github.com/pace-neutrons/Euphonic/pull/100#discussion_r517954830.

Add metadata to .json outputs and associated tests

---

CHANGELOG.rst
setup.py

The conda-forge CI isn't working with the current setup as it doesn't have =brew= available on Mac and the =gcc= binary on linux has a platform-dependent name.
These tweaks allow the environment CC to be used, and avoid the build script blowing up if homebrew is unavailable.
If this PR is accepted it would be helpful to make a Euphonic point release as soon as possible for use in the conda-forge package.

Adjust compiler settings, use CC if set and don't assume homebrew

---

CHANGELOG.rst
setup.py

I would like to make a release as soon as possible so that the setup.py tweaks are available from PyPI for conda builds.
We have added some significant features comparable to other 0.x releases, so I suggest incrementing to 0.5.0.
I have tried building this 0.5.0 release locally with release.py, was able to install and test the resulting .tar.gz package without issue. (I set the v0.5.0 tag locally, have not pushed the tag in case further changes are needed.)

Changelog update for 0.5.0 release

---

tests_and_analysis/LinuxJenkinsfile

Changes the `Jenkinsfile` to get the correct SHA1 for the commit which triggers a PR build (rather than the merge commit which github passes to Jenkins).

Correct SHA for PR in Jenkinsfile

---

CHANGELOG.rst
c/_euphonic.c
c/load_libs.c
c/load_libs.h
euphonic/force_constants.py
tests_and_analysis/test/euphonic_test/test_force_constants_calculate_qpoint_phonon_modes.py

This PR presents an alternative way to get a pointer to the LAPACK `zheevd` matrix eigensolver function. Instead of loading this from a shared library, it uses the [function pointers](https://docs.scipy.org/doc/scipy/reference/linalg.cython_lapack.html#module-scipy.linalg.cython_lapack) exposed by `scipy` for use by `cython`. These functions have the same Fortran calling convention as `zheevd_` which is loaded from the libraries but should point to whichever function `scipy`/`numpy` was compiled with on the user's system.
The PR:
* Removed searching / loading of shared libraries.
* Instead use the function pointers provided by scipy for use with Cython
* Also implement a simple caching mechanism using a global variable.
Fixes #149, #150

Change load_libs.c to use scipy cython refs

---

CHANGELOG.rst
doc/source/units.rst
euphonic/crystal.py
euphonic/debye_waller.py
euphonic/force_constants.py
euphonic/qpoint_frequencies.py
euphonic/spectra.py
euphonic/structure_factor.py
tests_and_analysis/test/euphonic_test/test_crystal.py
tests_and_analysis/test/euphonic_test/test_debye_waller.py
tests_and_analysis/test/euphonic_test/test_force_constants.py
tests_and_analysis/test/euphonic_test/test_qpoint_frequencies.py
tests_and_analysis/test/euphonic_test/test_qpoint_phonon_modes.py
tests_and_analysis/test/euphonic_test/test_spectrum1d.py
tests_and_analysis/test/euphonic_test/test_spectrum1dcollection.py
tests_and_analysis/test/euphonic_test/test_spectrum2d.py
tests_and_analysis/test/euphonic_test/test_structure_factor.py
tests_and_analysis/test/utils.py

Addresses #120
This isn't in need of a review as such, it's more of just a heads up. I haven't added any shape/type checking on the properties, I thought that would be inconsistent with other non-property attributes, we still only check on object creation. I think that's fine for now?
We could get shape checking for free on the properties by indexing into the internal attribute like:
```
@cell_vectors.setter
def cell_vectors(self, value):
self.cell_vectors_unit = str(value.units)
self._cell_vectors[:] = value.to('bohr').magnitude
```
But we don't do any checks when setting things like eigenvectors so I feel like that would be inconsistent.

Add property setters

---

euphonic/cli/powder_map.py
tests_and_analysis/test/data/script_data/powder-map.json
tests_and_analysis/test/script_tests/test_powder_map.py

After playing with the powder-map script for the workshop, I was finding it painful to have to regenerate plots just to change the intensities, so I've added some widgets to allow putting in min/max intensity without having to recalculate all the q-points. It seems to work well enough (although I can't get it to work via a Jupyter notebook).
I've tried for a while and couldn't find a good way to test it yet, but maybe that could be for another PR, its only on `euphonic-powder-map` and can be disabled so any damage should be minimal.

Add widget for changing intensity to powder-map plots

---

doc/source/index.rst

- Installation instructions currently live in index.rst
Hopefully this will help avoid frustration where e.g. pyyaml is not installed.
These dependencies are not included in the package so that a "lightweight" Euphonic dependency is possible for packages that bring their own force constants and make their own plots.
Closes #156

Add conda-forge installation to index.rst

---

CHANGELOG.rst
doc/source/powder-map-script.rst
euphonic/cli/dispersion.py
euphonic/cli/dos.py
euphonic/cli/intensity_map.py
euphonic/cli/powder_map.py
euphonic/cli/utils.py
euphonic/spectra.py
tests_and_analysis/test/euphonic_test/test_spectrum1d.py
tests_and_analysis/test/script_tests/test_dispersion.py
tests_and_analysis/test/script_tests/test_dos.py
tests_and_analysis/test/script_tests/test_intensity_map.py
tests_and_analysis/test/script_tests/test_powder_map.py

Partially addresses #130
I decided to just do the simple thing for now and just add a `--save-json` option to the CL tools, as this is sorely needed by the `euphonic-powder-map` tool and has been requested for quite a while...
In doing so I found a strange bug, in that the values produced by `euphonic.cli.utils._get_tick_labels` are actually of type `List[Tuple[np.int32, str]]` rather than using plain `int`, so it was not JSON serialisable! This is due to the call to `np.where`, which produces an array of type `np.int64`. I could've probably just fixed this in that function, but thought that setting the `x_tick_labels` on an existing object is actually probably a common thing to do, especially with values produced by `np.where`. So instead I fixed it in the `Spectrum` object itself, and …

Enable saving as JSON from CL tools

---

.github/workflows/build_upload_pypi_wheels.yml
.github/workflows/run_tests.yml
.github/workflows/test_release.yml
release_tox.ini
tox.ini

The upcoming `0.6.5` release of Euphonic will support Python versions `3.6-3.10`, this PR updates the CI and release scripts for those versions.
Regularly testing on Python 3.6, 3.7, 3.8, 3.9 and 3.10 is overkill and will make the CI take ages, so the tests for 3.8 and 3.9 will generally be skipped. If we run the CI explicitly via a workflow dispatch, tests for all versions will be run. We can do this just before a release to ensure everything works on all versions.

Update Python test/release versions

---

.github/workflows/build_upload_pypi_wheels.yml
.github/workflows/create-landing-page.yml
.github/workflows/run_tests.yml
.github/workflows/test_release.yml
release_tox.ini

Ready for review provided the PyPI builds in https://github.com/pace-neutrons/Euphonic/actions/runs/2630595376 pass (the Conda ones will probably still fail). Summary:
- Move from `RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64` to `pypa/cibuildwheel@v2.8.0` action to create manylinux wheels. Originally the manylinux builds where failing due to the issue described in https://github.com/pypa/manylinux issue 1309, meaning that an unversioned wheel was being created from verisoneer.  `cibuildwheel` is better maintained so has already caught and fixed this issue, and hopefully will do with any future issues.
- Added a workflow dispatch option which wont try and upload the wheels to PyPI, so we can create wheels without having to create a release.
- Switch from the …

Fix PyPI wheel builds

---

euphonic/__init__.py
tests_and_analysis/test/script_tests/test_dispersion.py

After installing Euphonic on an empty Python 3.9 conda environment I was getting an `ImportError` because packaging wasn't installed. I found that these imports in Euphonic are actually no longer used and are the last remaining references to the packaging library. Packaging is not in the Python standard library so we must remember to add it to dependencies if we're to use it again, it was omitted before. How we didn't notice this earlier I don't know, I guess we got lucky and other dependencies needed packaging so it was installed anyway.

Remove packaging imports

---

release_tox.ini

Python 3.7 conda support was dropped when 3.11 was added.
See https://github.com/conda-forge/conda-forge.github.io issue 1815.

Don't test Py 3.7 release for Conda

---

.github/workflows/build_upload_pypi_wheels.yml
.github/workflows/run_tests.yml
CHANGELOG.rst
release_tox.ini
tox.ini

#248 
Currently getting the error:
```
PackagesNotFoundError: The following packages are not available from current channels:
- python=3.11
Current channels:
- https://repo.anaconda.com/pkgs/main/linux-64
- https://repo.anaconda.com/pkgs/main/noarch
- https://repo.anaconda.com/pkgs/r/linux-64
- https://repo.anaconda.com/pkgs/r/noarch
```
Looks like Python 3.11 isn't available yet, but there is an issue https://github.com/ContinuumIO/anaconda-issues/issues/ issue 13082. Opening this PR as a reminder for now and will merge once Python 3.11 is available.
Tasks:

Test/release on Python 3.11

---

.github/workflows/run_tests.yml
.readthedocs.yml
CHANGELOG.rst
c/_euphonic.c
doc/requirements.txt

Change code to use the `Py_RETURN_NONE` macro to correctly increment the reference count to the `Py_None` object returned by the `calculate_phonons` C-extension.

Fix Py_None increment bug #270

---

euphonic/util.py

This logic was passing a size-1 vector of indices to a scalar index, which is no longer allowed as of version 1.25
The result was a hard-to-debug test failure because one of the script tests is checking that no warnings are raised: https://github.com/pace-neutrons/Euphonic/blob/48cbb0e06ec9c81016466c472bd57c9ea50e4442/tests_and_analysis/test/script_tests/test_optimise_dipole_parameter.py#L79
That testing approach could be improved to give better information, but this is less urgent than addressing a test failure that currently affects `master`.
(I did also clarify some control logic, as I that code block is being edited anyway...)

Address Numpy 1.25 deprecation warning

---

.github/workflows/build_upload_pypi_wheels.yml
.github/workflows/create-landing-page.yml
.github/workflows/run_tests.yml
.github/workflows/test_release.yml
.readthedocs.yml
doc/source/installation.rst
release_tox.ini
setup.py
tests_and_analysis/minimum_euphonic_requirements.txt
tox.ini

Closes #278 
This PR should focus on mechanics of version bump; subsequent PRs can introduce new goodies.

Drop python 3.7 support, bump Scipy, Pint, h5py requirements

---

CHANGELOG.rst
euphonic/styles/__init__.py
setup.py
tests_and_analysis/minimum_euphonic_requirements.txt

This line was causing some deprecation warnings. I think this is the right way to modernise it?

Drop deprecated pkg_resources

---

CHANGELOG.rst
doc/source/python-api.rst
doc/source/spectra.rst
euphonic/broadening.py
euphonic/crystal.py
euphonic/force_constants.py
euphonic/plot.py
euphonic/powder.py
euphonic/qpoint_frequencies.py
euphonic/qpoint_phonon_modes.py
euphonic/readers/castep.py
euphonic/readers/phonopy.py
euphonic/spectra.py
euphonic/structure_factor.py
euphonic/util.py

Using some features of Python 3.8+ and newer Numpy
I tried not to go too crazy, there are more places where assignment expressions (i.e. walrus) could be used to save a line but overall flow and clarity don't really benefit.

Clean up a bit using new dependencies

---

CHANGELOG.rst
euphonic/io.py
tests_and_analysis/test/euphonic_test/test_qpoint_phonon_modes.py

Bugfix: load QpointPhononModes with one q-point from JSON

---

CHANGELOG.rst
euphonic/util.py

Some sanity-checking has been added to spglib and now this scenario leads to a TypeError before the SymmetryDetectionError is reached.
This has been causing test failures on unrelated branches as the CI is using the new version of spglib
closes #297

Spglib 2.4 compatibility: handle TypeError when passing empty cell

---

CHANGELOG.rst
euphonic/readers/castep.py
setup.py

Adds a more helpful error message if users try to use old castep_bin file (pre Castep-17.1).
An alternative fix would involve calculating the `supercell_origins` field. Some [code](https://github.com/pace-neutrons/Euphonic/blob/7608b14f7024ebb240c079ab336805e6a190b8f1/euphonic/readers/phonopy.py#L765-L768) used in the phonopy reader could possibly be re-used for this.
Fixes #295

Add error for old castep_bin files

---

.github/workflows/build_upload_pypi_wheels.yml
.github/workflows/run_tests.yml
.github/workflows/test_release.yml
CHANGELOG.rst
euphonic/force_constants.py
setup.py
tests_and_analysis/test/euphonic_test/test_broadening.py
tox.ini

With Numpy 2.0, np.unique returns a 2-D array when applied to q-points. This in turn gets broadcast and adds an extra dimension to the frequency/mode arrays, causing all kinds of chaos.
Flattening the array here should be a no-op for Numpy <2 and fix the issue.

Flatten q-point indices for compatibility with Numpy 2.0

---

.github/workflows/build_upload_pypi_wheels.yml
.github/workflows/run_tests.yml
.github/workflows/test_release.yml
CHANGELOG.rst
euphonic/util.py

Test updates to Brille build system https://github.com/brille/brille/issues/100

Test Brille fix

---

.github/workflows/build_upload_pypi_wheels.yml
.github/workflows/create-landing-page.yml
.github/workflows/run_tests.yml
.github/workflows/test_release.yml
.readthedocs.yml
doc/requirements.txt
doc/source/cite.rst
doc/source/installation.rst
euphonic/__init__.py
euphonic/readers/castep.py
euphonic/styles/__init__.py
euphonic/util.py
release_tox.ini
setup.py
tests_and_analysis/minimum_euphonic_requirements.txt
tests_and_analysis/test/euphonic_test/test_install.py
tests_and_analysis/test/run_tests.py
tox.ini

Python 3.9 isn't _quite_ dead yet but supporting it on ARM Mac is quite annoying. 3.12 is very much out there in production now.

Drop Python 3.8, 3.9 and add Python 3.12

---

.github/workflows/build_upload_pypi_wheels.yml
.github/workflows/run_tests.yml
CHANGELOG.rst
setup.py
tests_and_analysis/minimum_euphonic_requirements.txt
tox.ini

While transitioning to Numpy 2.0 it is helpful to reduce the range of versions being used and tested. As we are changing other requirements in this release, it is a good time to bump Numpy.
Here we also update the build/release workflow to add Python 3.12 and build with Numpy 2.0; these builds _should_ also work with all the supported numpy 1.x.

Bump numpy requirement to 1.24, matching Mantid

---

euphonic/brille.py
euphonic/cli/utils.py
tests_and_analysis/test/euphonic_test/test_qpoint_frequencies.py
tests_and_analysis/test/euphonic_test/test_spectrum1d.py
tests_and_analysis/test/euphonic_test/test_spectrum2d.py
tests_and_analysis/test/euphonic_test/test_util.py
tests_and_analysis/test/script_tests/test_intensity_map.py
tests_and_analysis/test/script_tests/test_optimise_dipole_parameter.py
tests_and_analysis/test/script_tests/test_powder_map.py
tests_and_analysis/test/script_tests/utils.py
tests_and_analysis/test/utils.py

- Spglib 2.5 deprecation warnings; when caused by Euphonic, we can solve the compatibility issue by converting to a dict. When caused by a dependency, suppress the warning.
- Filter out expected warnings from certain tests in a more systematic way
- Avoid a Matplotlib warning when calling tight_layout() on a plot with a colourbar... by not doing that.
- Replace noisy implicit filling of masked values with NaN with explicit filling
There is a divide-by-zero warning which I think has its roots in nasty pint/spectroscopy units hackery. That is not just an artifact and should be dealt with in a separate PR.

Clean up some low-hanging warnings in test suite

---

CHANGELOG.rst
euphonic/__init__.py
euphonic/broadening.py
euphonic/data/reciprocal_spectroscopy_definitions.txt
euphonic/readers/castep.py
euphonic/spectra.py
euphonic/validate.py
tests_and_analysis/test/data/spectrum1dcollection/lzo_222_full_castep_adaptive_dos.json
tests_and_analysis/test/data/spectrum1dcollection/quartz_554_full_castep_adaptive_dos.json
tests_and_analysis/test/euphonic_test/test_castep_reader.py
tests_and_analysis/test/euphonic_test/test_spectrum1d.py
tests_and_analysis/test/utils.py
tests_and_analysis/tox_requirements.txt

It looks like spectral intensities are sometimes handled in energy units (such as when imported from CASTEP DOS). If these are converted to/from their proper (reciprocal energy) units, this can cause divide-by-zero errors as pint performs a wavenumber <-> wavelength conversion and takes the reciprocal of the spectral intensities, including empty bins.
Here we introduce another mechanism for dealing with spectral units: a few extra unit conversions in a special "reciprocal_spectroscopy" context (which comes an "rs" alias for convenience). This stops Pint from choking on the `1/(1/cm) <-> 1/meV` conversions.
The broadening system is made a bit more robust; previously the variable-width broadening assumed that things can always be converted to energy units.
Perhaps the most serious issue …

Improve handling of spectral units

---

.github/workflows/test_release.yml

The latest version of download-artifact v4 includes an important security fix.
Version numbers of upload- and download- artifact are supposed to match.
Other actions are already using these versions but this one was overlooked.

Update github action versions in test_release

---

CHANGELOG.rst
euphonic/spectra.py
tests_and_analysis/test/euphonic_test/test_spectrum1dcollection.py
tests_and_analysis/test/euphonic_test/test_spectrum2dcollection.py

When filtering or otherwise manipulating spectra from an existing collection, we can be confident the axes remain consistent. The safety checks are quite expensive so this should be a useful optimisation.

Allow "unsafe" (faster) Spectrum1DCollection.from_spectra()

---

CHANGELOG.rst
euphonic/spectra.py

Iterating on SpectrumCollection objects is currently quite expensive, which limits the feasibility of processing them with functional-programming-style filters, pipelines etc. Currently in Abins prototypes I am using workarounds that access or construct raw numpy arrays. It would be nice if that wasn't necessary!
So far we just have a proof of concept: instead of constructing with the relatively slow `__init__()` method, we can use `__new__()` and bypass the safety checks. As we are constructing from known-good data this _should_ be ok...

Faster indexing/iteration for spectrum collections

---

.github/workflows/run_tests.yml

Alternative to #321 : parallelism at the `tox` level
Let's see if we get a more impressive speedup by distributing the tox environments over separate processors.
Depends on #324

run_tests workflow: use parallel tox

---

.gitattributes
.github/workflows/build_upload_pypi_wheels.yml

Depends on #337 
meson-python uses git-archive to create the sdist. Some of euphonic's test files are on the large side and we don't need to include them with every copy of the source.
This does have the downside that git-archive can no longer be used to produce a copy of the source with tests, but we weren't using that anyway.

Reduce source distribution size

---

.github/workflows/build_upload_pypi_wheels.yml
.github/workflows/run_tests.yml
.github/workflows/set_version.yml
CITATION.cff
euphonic/version.py

Developing a github action that sets the version number in all the relevant places, for use in the release process.
This is part of #326

Version number action

---

.github/workflows/set_version.yml
CHANGELOG.rst
CITATION.cff

This post-release makes some changes to the source-distribution build process:
- A bug is fixed in the version-numbering script; this particularly affected Windows
- A copies of the unit tests and documentation were mistakenly included
in tarballs, making them excessively large. This is no longer present.

Release 1.4.0.post1

---

.github/workflows/test_release.yml
build_utils/release_tox.ini
tests_and_analysis/minimum_euphonic_requirements_mac.txt
tox.ini

Current status:
- All conda tests failing (this is fine, the conda-forge package is not done yet)
- Ubuntu pypi-py310-min fails because it can't build spglib. The `ModuleNotFoundError: No module named 'distutils.msvccompiler'` error seems to be related to numpy/distutils versions.
- Windows pypisource-py310 and pypisource-py312 fail to build the Euphonic package, probably an environment/Meson issue
- macos-latest pypi-py310-min fails because it can't build spglib or h5py. I think there are no ARM wheels for the old versions and we haven't set up an appropriate environment to build them (e.g. with libhdf5 an old C compiler)
- macos-13 pypi-py310-min fails because it can't build spglib

Update release tests for new framework

---

.github/workflows/test_release.yml
build_utils/release_tox.ini

Not backwards compatible with prior releases, requires #324 release.
Cannot test without #324 release.

Use tox 4 for release testing

---

.github/workflows/run_tests.yml
.github/workflows/test_checkout_one_os.yml

Based on https://stackoverflow.com/a/73953210
Closes #341

Refactor test matrix: most logic at top level, call reusable workflow

---

build_utils/pypi_release_tox.ini
tox.ini

Use constraints file in tox min-requirements. Also attempt to simplify testing commands.
Closes #345

Use constraints file in tox

---

.github/workflows/run_tests.yml
CHANGELOG.rst
CITATION.cff
euphonic/version.py

Pre-release to test release tool updates
- Need to merge into master to bring the tweaks to run_tests
- CHANGELOG was messed up: pre-release shouldn't appear in changelog. Incoming PR to fix that.
- Push to PyPI failed because release.yml didn't have permission from the PyPI side. That has now been fixed.
I intend to do a 1.4.1rc2 release the checks everything is working before the "real" 1.4.1 release.

Pre release 1.4.1 rc

---

CITATION.cff
euphonic/version.py

It looks like everything worked:
https://github.com/pace-neutrons/Euphonic/releases/tag/v1.4.1rc2
https://pace-neutrons.github.io/Euphonic/versions/v1.4.1rc2.html
https://pypi.org/project/Euphonic/1.4.1rc2/
CHANGELOG still shows as Unreleased, that should change on full release.

Release workflow tuning: 1.4.1rc2 release

---

CHANGELOG.rst
euphonic/spectra/__init__.py

Closes #374 
This was a rather subtle API break but it affects some Abins refactoring. Even if we don't inherit from Spectrum it is useful as a type annotation.

Expose base Spectrum to euphonic.spectra namespace

---

.github/workflows/test_gcc14.yml
CHANGELOG.rst
c/_euphonic.c
c/py_util.c
pyproject.toml

Closes #351 
[PyObject](https://docs.python.org/3/c-api/structures.html#c.PyObject)s are clever: although C doesn't really have "inheritance", their pointers work as a common interface to more specific Python object types as all these structures have a PyObject as the first component. This way the pointer always goes to something that looks like a PyObject!
Compilers are understandably twitchy about the ensuing signature mismatch when we take a function with signature
`Pyobject *PyDict_GetItemString(PyObject *p, const char *key)`
and pass it a `*PyDictObject` as the first argument. Since GCC14 this has become a hard error; the solution is to explicitly cast pointers from their specialised class to *PyObject.

Fix incompatible-pointer-types

---

.github/workflows/run_tests.yml
.github/workflows/test_gcc14.yml
euphonic/cli/dispersion.py
euphonic/cli/dos.py
euphonic/cli/intensity_map.py
euphonic/cli/utils.py
euphonic/crystal.py
euphonic/force_constants.py
euphonic/io.py
euphonic/readers/phonopy.py
euphonic/sampling.py
euphonic/validate.py
pyproject.toml
tests_and_analysis/test/euphonic_test/test_castep_reader.py
tests_and_analysis/test/euphonic_test/test_crystal.py
tests_and_analysis/test/euphonic_test/test_force_constants.py
tests_and_analysis/test/euphonic_test/test_force_constants_calculate_qpoint_frequencies.py
tests_and_analysis/test/euphonic_test/test_force_constants_calculate_qpoint_phonon_modes.py
tests_and_analysis/test/euphonic_test/test_qpoint_frequencies.py
tests_and_analysis/test/script_tests/test_powder_map.py
tests_and_analysis/test/utils.py

Pylint has been complaining for a while about some stuff that is easy to fix but would clutter other PRs. They should be done in manageable batches in separate PRs.

Linting: whitespace, negation, type comparison, mutable defaults, staticmethods

---

CHANGELOG.rst
euphonic/spectra/collections.py
tests_and_analysis/test/euphonic_test/test_spectrum2dcollection.py

These methods were left out, which became apparent when trying to use them in an Abins refactor...

Add  "get_bin_edges", "get_bin_centres" to Spectrum2DCollection

---

CHANGELOG.rst
build_utils/release.py
build_utils/version.py
euphonic/broadening.py
euphonic/cli/brille_convergence.py
euphonic/cli/show_sampling.py
euphonic/cli/utils.py
euphonic/force_constants.py
euphonic/plot.py
euphonic/qpoint_phonon_modes.py
euphonic/readers/castep.py
euphonic/readers/phonopy.py
euphonic/structure_factor.py
euphonic/util.py
pyproject.toml
tests_and_analysis/test/euphonic_test/test_broadening.py
tests_and_analysis/test/euphonic_test/test_calculate_structure_factor.py
tests_and_analysis/test/euphonic_test/test_plot.py
tests_and_analysis/test/euphonic_test/test_spectrum1dcollection.py
tests_and_analysis/test/euphonic_test/test_structure_factor.py
tests_and_analysis/test/script_tests/test_brille_convergence.py
tests_and_analysis/test/script_tests/test_powder_map.py
tests_and_analysis/test/script_tests/utils.py
tests_and_analysis/test/utils.py

Mostly trivial linter stuff, but:
- the reworked loop in broadening.py is a more substantial change, but should be safer in the end.
- found a bug in CASTEP mode gradients; units parameter ignored. This shouldn't have led to inconsistent results as returned data had consistent units and values; but if you blindly used the results with provided units there could be trouble.

387 more lint, small bugfix

---

CHANGELOG.rst
pyproject.toml
tests_and_analysis/test/pytest.ini

Currently the test suite produces a lot of warnings about the "marks" used to control which subset of tests runs.
I see these when running locally, but not in the CI logs. Not sure if they are suppressed somehow or it is a matter of different pytest versions, but it doesn't hurt to clear them up either way.
(Tox tends to hide the pytest warnings but you can see them in the GCC14 CI logs, which call the run_tests.py script directly. e.g. https://github.com/pace-neutrons/Euphonic/actions/runs/15066709878/job/42353084713)

Register pytest marks in pyproject.toml

---

euphonic/broadening.py
euphonic/cli/dispersion.py
euphonic/cli/optimise_dipole_parameter.py
euphonic/cli/utils.py
euphonic/crystal.py
euphonic/force_constants.py
euphonic/io.py
euphonic/plot.py
euphonic/qpoint_phonon_modes.py
euphonic/readers/castep.py
euphonic/readers/phonopy.py
euphonic/spectra/collections.py
euphonic/structure_factor.py
pyproject.toml
tests_and_analysis/test/euphonic_test/test_plot.py
tests_and_analysis/test/script_tests/test_intensity_map.py
tests_and_analysis/test/script_tests/test_powder_map.py

Depends on #408 
This mostly concerns line lengths and comparison with `is`.
Line length is a controversial topic and I'm open to loosening Euphonic a little from 79 to 90 or 100, say. But it should be done systematically, using a formatter to expand existing code where appropriate.
For now I have made exceptions for the test suite and build scripts, as these seem to be frequent but not egregious offenders: i.e. the writers probably had a limit in place, but one that is larger than 79.

Linting: pycodestyle-error

---

pyproject.toml
tests_and_analysis/test/script_tests/utils.py

Now that "E" has been sorted out, `tryceratops` was a lot easier to enable than expected.

Linting: tryceratops

---

doc/requirements.txt
tests_and_analysis/tox_requirements.txt

In response to CVE-2025-47273
As Euphonic does not directly use setuptools this should only affect CI, so not a breaking change.

Security: Bump setuptools to 78.1.1 for docs build and test runs

---

CHANGELOG.rst
euphonic/force_constants.py
euphonic/qpoint_phonon_modes.py
euphonic/readers/phonopy.py
euphonic/util.py
pyproject.toml

~~Based on top of #417 , rebase on master when that is done.~~
- Don't use einsum where a matmul (@) will do the job. There can be a performance benefit to matmul as it will be dispatched to the appropriate BLAS routine more reliably. But more importantly it makes some operations easier to read and easier to learn the conventions at work. The more complex einsums are left to stand out as needing closer scrutiny.
- There are a few places `np.newxis` is aliased to `ax` to save space. That's quite confusing because `ax` usually means a Matplotlib axis. And it is unnecesssary as `np.newxis` is just an alias to `None` and this is compact enough already.

Tidy up some numpy code
